# Generated by Django 3.0.2 on 2020-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('proteinName', models.TextField()),
                ('proteinIndex', models.IntegerField()),
            ],
        ),
    ]
